version: '3.8'

services:
  nginx:
    image: nginx:1.26
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - BLUE_HOST=app_blue
      - GREEN_HOST=app_green
      - BLUE_PORT=${PORT}
      - GREEN_PORT=${PORT}
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:${PORT}"

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:${PORT}"
